# Site settings
title: "jinbread labs"
email: jinbread.lee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  jinbread.co &copy 2014-2017
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jinbread.github.io" # the base hostname & protocol for your site
github_username:  jinbread

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: pygments

# Gems
plugins: [jekyll-paginate]

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
